// Temporary mock data for development while backend is being fixed

export const mockTransfers = [
  {
    uuid: '1',
    title: 'Kylian Mbappé Completes €180M Move to Real Madrid',
    content: 'French superstar Kylian Mbappé has officially completed his long-awaited move to Real Madrid in a deal worth €180 million. The 25-year-old forward signed a five-year contract with Los Blancos, ending his successful stint at Paris Saint-Germain.',
    league: 'La Liga',
    player_name: 'Kylian Mbappé',
    current_club: 'Paris Saint-Germain',
    destination_club: 'Real Madrid',
    transfer_fee: '€180M',
    transfer_type: 'Permanent',
    transfer_status: 'confirmed',
    published_date: '2025-01-15T10:00:00Z',
    created_at: '2025-01-15T10:00:00Z',
    images: ['https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&h=600&fit=crop'],
    original_link: 'https://example.com/mbappe-real-madrid',
    tags: ['Real Madrid', 'PSG', 'Transfer', 'La Liga'],
    status: 'published'
  },
  {
    uuid: '2',
    title: 'Manchester United Target €90M Rated Striker from Serie A',
    content: 'Manchester United are reportedly preparing a €90 million bid for Napoli striker Victor Osimhen. The Nigerian international has been in exceptional form this season, scoring 28 goals in all competitions.',
    league: 'Premier League',
    player_name: 'Victor Osimhen',
    current_club: 'Napoli',
    destination_club: 'Manchester United',
    transfer_fee: '€90M',
    transfer_type: 'Permanent',
    transfer_status: 'rumor',
    published_date: '2025-01-14T15:30:00Z',
    created_at: '2025-01-14T15:30:00Z',
    images: ['https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800&h=600&fit=crop'],
    original_link: 'https://example.com/osimhen-united',
    tags: ['Manchester United', 'Napoli', 'Transfer', 'Premier League'],
    status: 'published'
  },
  {
    uuid: '3',
    title: 'Chelsea Close to Signing €80M Rated Midfielder',
    content: 'Chelsea are on the verge of completing the signing of Brighton midfielder Moises Caicedo for a fee of €80 million. The Ecuadorian has been one of the standout performers in the Premier League this season.',
    league: 'Premier League',
    player_name: 'Moises Caicedo',
    current_club: 'Brighton',
    destination_club: 'Chelsea',
    transfer_fee: '€80M',
    transfer_type: 'Permanent',
    transfer_status: 'confirmed',
    published_date: '2025-01-13T12:00:00Z',
    created_at: '2025-01-13T12:00:00Z',
    images: ['https://images.unsplash.com/photo-1579952363873-27d3bfad9c0d?w=800&h=600&fit=crop'],
    original_link: 'https://example.com/caicedo-chelsea',
    tags: ['Chelsea', 'Brighton', 'Transfer', 'Premier League'],
    status: 'published'
  },
  {
    uuid: '4',
    title: 'Liverpool Eye €120M Move for Brazilian Winger',
    content: 'Liverpool are reportedly interested in signing Barcelona winger Raphinha for a fee of €120 million. The Brazilian international has been impressive since joining the Catalan club.',
    league: 'Premier League',
    player_name: 'Raphinha',
    current_club: 'Barcelona',
    destination_club: 'Liverpool',
    transfer_fee: '€120M',
    transfer_type: 'Permanent',
    transfer_status: 'rumor',
    published_date: '2025-01-12T09:15:00Z',
    created_at: '2025-01-12T09:15:00Z',
    images: ['https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800&h=600&fit=crop'],
    original_link: 'https://example.com/raphinha-liverpool',
    tags: ['Liverpool', 'Barcelona', 'Transfer', 'Premier League'],
    status: 'published'
  },
  {
    uuid: '5',
    title: 'Arsenal Complete Deal for French Defender',
    content: 'Arsenal have successfully completed the signing of Monaco defender Axel Disasi for €45 million. The French center-back will strengthen the Gunners defense for the upcoming season.',
    league: 'Premier League',
    player_name: 'Axel Disasi',
    current_club: 'Monaco',
    destination_club: 'Arsenal',
    transfer_fee: '€45M',
    transfer_type: 'Permanent',
    transfer_status: 'completed',
    published_date: '2025-01-11T14:45:00Z',
    created_at: '2025-01-11T14:45:00Z',
    images: ['https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=600&fit=crop'],
    original_link: 'https://example.com/disasi-arsenal',
    tags: ['Arsenal', 'Monaco', 'Transfer', 'Premier League'],
    status: 'published'
  },
  {
    uuid: '6',
    title: 'Bayern Munich Secure €70M Signing from Bundesliga Rival',
    content: 'Bayern Munich have completed the signing of Borussia Dortmund midfielder Jude Bellingham for €70 million. The English international chose Bayern over several other European giants.',
    league: 'Bundesliga',
    player_name: 'Jude Bellingham',
    current_club: 'Borussia Dortmund',
    destination_club: 'Bayern Munich',
    transfer_fee: '€70M',
    transfer_type: 'Permanent',
    transfer_status: 'confirmed',
    published_date: '2025-01-10T11:30:00Z',
    created_at: '2025-01-10T11:30:00Z',
    images: ['https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&h=600&fit=crop'],
    original_link: 'https://example.com/bellingham-bayern',
    tags: ['Bayern Munich', 'Borussia Dortmund', 'Transfer', 'Bundesliga'],
    status: 'published'
  }
]

export const mockLeagues = [
  { id: 'premier-league', name: 'Premier League', country: 'England', slug: 'premier-league', logoUrl: '/logos/leagues/premier-league.png' },
  { id: 'la-liga', name: 'La Liga', country: 'Spain', slug: 'la-liga', logoUrl: '/logos/leagues/la-liga.png' },
  { id: 'serie-a', name: 'Serie A', country: 'Italy', slug: 'serie-a', logoUrl: '/logos/leagues/serie-a.png' },
  { id: 'bundesliga', name: 'Bundesliga', country: 'Germany', slug: 'bundesliga', logoUrl: '/logos/leagues/bundesliga.png' },
  { id: 'ligue-1', name: 'Ligue 1', country: 'France', slug: 'ligue-1', logoUrl: '/logos/leagues/ligue-1.png' }
]
